import oclif from 'eslint-config-oclif'
import prettier from 'eslint-config-prettier'

export default [
  ...oclif,
  prettier,
  {
    rules: {
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/ban-types': 'off',
      '@typescript-eslint/no-empty-object-type': 'off',
      'no-prototype-builtins': 'off',
      '@typescript-eslint/no-empty-function': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/no-var-requires': 'off',
      '@typescript-eslint/no-use-before-define': 'off',
      '@typescript-eslint/no-unused-vars': 'warn',
      'no-buffer-constructor': 'error',
      'no-import-assign': 'warn',
      'perfectionist/sort-objects': 'off',
      'object-shorthand': 'off',
      'perfectionist/sort-interfaces': 'off',
      'perfectionist/sort-union-types': 'off',
      'perfectionist/sort-named-imports': 'off',
      'perfectionist/sort-imports': 'off',
      'unicorn/no-process-exit': 'off',
      'n/no-process-exit': 'off',
      'n/no-unpublished-bin': 'off',
      'padding-line-between-statements': 'off',
      '@stylistic/padding-line-between-statements': 'off',
      '@stylistic/lines-between-class-members': 'off',
      'arrow-body-style': 'off',
      'perfectionist/sort-classes': 'off',
      'camelcase': 'off',
      'no-await-in-loop': 'warn',
      'dot-notation': 'off',
      'perfectionist/sort-intersection-types': 'off',
      'unicorn/no-for-loop': 'off',
      'perfectionist/sort-object-types': 'off',
      'max-params': 'off',
      'complexity': 'off',
      'unicorn/better-regex': ['error', {sortCharacterClasses: false}],
      'unicorn/no-negated-condition': 'off',
      'unicorn/prefer-string-raw': 'off',
      'unicorn/escape-case': 'off',
      'perfectionist/sort-sets': 'off',
      'prefer-promise-reject-errors': 'warn',
      'mocha/consistent-spacing-between-blocks': 'off',
      '@typescript-eslint/ban-ts-comment': 'off',
      '@typescript-eslint/no-wrapper-object-types': 'off',
      'perfectionist/sort-switch-case': 'off',
      'unicorn/catch-error-name': 'off',
      'unicorn/prefer-node-protocol': 'off',
      'unicorn/no-array-for-each': 'off',
      'import/default': 'off',
      'n/no-extraneous-import': 'off',
    },
  },
  {
    files: ['**/*.ts'],
    rules: {
      'id-blacklist': ['error', 'exports'],
    },
  },
  {
    files: ['test/**/*.ts'],
    languageOptions: {
      globals: {
        Config: 'readonly',
      },
    },
  },
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      '**/*.d.ts',
      'coverage/**',
      'test/**'
    ],
  },
]
